#!/usr/bin/env python3

# Simple calculator

def main(): # Wrapper function
    info = "This is primitive calculator.\n" \
           "To perform a specific operation,\n" \
           "step by step enter the first and second number,\n " \
           "and then one of the special symbols:\n" \
           "+ (addition), - (subtraction), * (multiplication), / (division)\n"
    print(info)

    while True: # Iterates until the user wants to exit
        first_number = int(input("Please, enter first number: "))
        second_number = int(input("Please, enter second number: "))
        operation = input("Please, enter one of the special symbols: ")

        print(calculator(first_number, second_number, operation))
        solution = input("Do you want to continue? (Enter Yes or No): ")
        if solution == 'Yes':
            continue
        elif solution == 'No':
            break
        else:
            while True:
                print("Please, enter Yes or No")
                solution = input("Do you want to continue? (Enter Yes or No): ")
                if solution == 'Yes':
                    break
                elif solution == 'No':
                    quit()


def calculator(first_number, second_number, operation):
    """
    Returns: first_number operation second_number = 'x',
    where 'x' is the computed value according
    to the selected operator
    """
    if operation == '+':
        return(str(first_number) + ' ' + operation + ' ' + str(second_number) + ' = ' + str(first_number + second_number))
    elif operation == '-':
        return(str(first_number) + ' ' + operation + ' ' + str(second_number) + ' = ' + str(first_number - second_number))
    elif operation == '*':
        return(str(first_number) + ' ' + operation + ' ' + str(second_number) + ' = ' + str(first_number * second_number))
    elif operation == '/':
        return(str(first_number) + ' ' + operation + ' ' + str(second_number) + ' = ' + str(first_number / second_number))


if __name__ == '__main__':
    main()
